version: '3.8'
services:
  dev:
    build: .
    command: sh -c "tail -f /dev/null"
    working_dir: /src
    volumes:
      - ./:/src:delegated
      - /src/node_modules
      - /src/dist
      - /src/.yarn/cache
      - ~/.ssh:/root/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 0.0.0.0:4200:4200
      - 0.0.0.0:3000:3000
  postgres:
    image: postgres:17.2
    environment:
      POSTGRES_USER: www_user
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: digital_www_pwa
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres_data:
